-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Breeze_Light")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    ecosystem = {
        no_donation_nag = true,
        no_update_news = true,
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(c0bfbcff)", "rgba(ffffffff)"},
                angle = 45,
            },
        },
        resize_on_border = true,
    },
    misc = {
        animate_manual_resizes = true,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "-1920x135",
    scale = 1,
    cm = "srgb",
})

-- Window rules
hl.window_rule({
    match = {
        class = "^(xdg\\-desktop\\-portal\\-gtk)$",
    },
    size = "1038 655",
    center = true
})
